"""Netlist helpers for update_pcb_from_schematic, and the wx guard for pcbnew scripts.

KiCad's SWIG bindings expose no netlist reader (checked 9.0.8 and the 10.0
branch), so pcb._apply_netlist_cst reimplements the F8 update in-process,
through the CST, and imports the pure helpers below.

Stdlib-only, and that is load-bearing rather than tidy: each pcbnew script
built on _freerouting.wx_app_prelude imports this module BY NAME, as a
top-level module off an injected sys.path, to reach _ensure_wx_app under
KiCad's interpreter, which has none of this package's dependencies.
"""

from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET


def parse_netlist(path: str) -> tuple[list[dict], list[dict]]:
    """Parse a kicad-cli XML netlist into (components, nets).

    components: [{ref, value, footprint, path}] — footprint "" when unassigned;
    path is the sheetpath+symbol KIID chain for GUI F8 linkage. A multi-unit
    symbol's <tstamps> lists every unit's KIID, space-separated, and the path
    takes the first one, as KiCad's own update does: a footprint has one
    identity, and the whole list written as its path was a token pcbnew
    cannot parse, so it gave the footprint a fresh random KIID on every load
    and the footprint was linked to no unit at all.
    nets: [{name, nodes: [(ref, pin), ...]}] — the netlist @code is ignored;
    net names are the only identity that survives onto the board.
    """
    # stdlib ET on purpose: the input is generated by kicad-cli into a temp
    # dir moments earlier (never attacker-supplied), and this module must stay
    # stdlib-only (see the module docstring), so defusedxml is not an option.
    root = ET.parse(path).getroot()
    components = []
    for comp in root.findall("./components/comp"):
        sheetpath = comp.find("sheetpath")
        prefix = sheetpath.get("tstamps", "/") if sheetpath is not None else "/"
        units = (comp.findtext("tstamps") or "").split()
        tstamp = units[0] if units else ""
        components.append(
            {
                "ref": comp.get("ref") or "",
                "value": comp.findtext("value") or "",
                "footprint": comp.findtext("footprint") or "",
                "path": (prefix.rstrip("/") + "/" + tstamp) if tstamp else "",
            }
        )
    nets = []
    for net in root.findall("./nets/net"):
        name = net.get("name") or ""
        if not name:
            continue
        nodes = [(n.get("ref") or "", n.get("pin") or "") for n in net.findall("node")]
        nets.append({"name": name, "nodes": nodes})
    return components, nets


def resolve_pretty(lib: str, lib_dirs: list[str]) -> str | None:
    """Resolve a footprint library nickname to its .pretty directory.

    A lib dir either IS the .pretty (basename match) or CONTAINS it
    (system footprints dir with many .pretty subdirs).
    """
    want = f"{lib}.pretty"
    for d in lib_dirs:
        if os.path.basename(os.path.normpath(d)) == want:
            return d
        cand = os.path.join(d, want)
        if os.path.isdir(cand):
            return cand
    return None


def grid_slot(k: int, ax: float, ay: float, pitch: float) -> tuple[float, float]:
    """Deterministic cluster slot for the k-th newly added footprint.

    10 columns, fixed pitch, growing downward (+Y) from anchor (ax, ay).

    Unit-agnostic, and it has to be: it was written for pcbnew, which works
    in integer nanometres, and the CST import calls it in millimetres.
    """
    # ponytail: fixed 10mm pitch, big footprints may overlap in the cluster;
    # courtyard-aware packing if it ever matters
    return ax + (k % 10) * pitch, ay + (k // 10) * pitch


def new_summary() -> dict:
    """Zeroed result schema — must mirror models.UpdatePcbResult exactly."""
    return {
        "status": "ok",
        "added": [],
        "value_updated": [],
        "fpid_changed": [],
        "stale_footprints": [],
        "stale_removed": [],
        "nets_added": 0,
        "nets_removed": 0,
        "pads_bound": 0,
        "orphaned_tracks": 0,
        "orphaned_zones": 0,
        "skipped": [],
        "warnings": [],
    }


# apply() lived here, and its pcbnew.SaveBoard was the last thing writing a
# user's own board outside the byte-preserving substrate. pcb._apply_netlist_cst
# does that work now, in-process and through the CST. What is left is what the
# rest of the package still needs from this module: the pure netlist and layout
# helpers above, which pcb.py imports directly, and _ensure_wx_app below, which
# the other pcbnew subprocesses reach by importing this module BY NAME off an
# injected sys.path (see _freerouting.wx_app_prelude). That is why the module
# keeps this name and its stdlib-only imports even though the netlist import
# itself no longer runs under pcbnew.


def _ensure_wx_app() -> None:
    """Give wxWidgets an application object before pcbnew can ask for one.

    pcbnew is a GUI library used here without a GUI. Most of its API never
    notices, which is why the old netlist script ran for months without one,
    but anything reaching wxStandardPaths::Get() asserts, and on macOS that
    assert kills the process rather than warning:

        ./src/common/stdpbase.cpp(59): assert "traits" failed in Get():
        create wxApp before calling this

    Seen twice on the macOS runner, both times on the --delete-stale run of
    TestUpdatePcbE2E, both times fixed by re-running, which is what made it look
    like flake. It is not: the process exits non-zero, so the caller's
    returncode check is right to fail, and the stderr carries no Python
    traceback because nothing Python raised.

    wx ships inside KiCad's own interpreter, so this adds no dependency
    (measured: wxPython 4.2.2 / wxWidgets 3.2.8 alongside pcbnew 9.0.8).
    redirect=False matters, because the default sends stdout to a GUI window
    and fill_zones reads the computed fills from stdout.

    Creating one is skipped where there is no display to open, and that check
    has to come first rather than being left to a try/except. The first version
    of this did leave it to one, on the assumption that a failure would raise
    something catchable. It does not: on a headless Linux runner wxPython exits
    the process with "Unable to access the X Display, is $DISPLAY set
    properly?", which took eight passing E2E tests red. A latent problem became
    a certain one, which is exactly what the guard was supposed to prevent.

    So the ceiling is real and is worth stating plainly: a display-less Linux
    host gets no wxApp and keeps whatever behaviour it had, which is a suite
    that passes today. Windows and macOS, where the assert has actually been
    observed, both have a display whenever a user is running this.
    """
    if sys.platform not in ("win32", "darwin") and not (
        os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY")
    ):
        return
    try:
        import wx  # pyright: ignore[reportMissingImports] — ships with KiCad
    except ImportError:
        return
    try:
        app = wx.App.Get() or wx.App(False)
        # wxPython installs its assert handler through wxApp, so until one
        # exists the raw C++ handler runs. On Windows that is a modal "wxWidgets
        # Debug Alert" dialog on the user's desktop, and this subprocess has
        # nobody to click it: the tool call blocks until the caller's 120s
        # timeout. Route any later assert to the log instead, where it reaches
        # stderr and the caller reports it.
        mode = getattr(wx, "APP_ASSERT_LOG", None)
        if mode is not None and hasattr(app, "SetAssertMode"):
            app.SetAssertMode(mode)
    except Exception as exc:  # noqa: BLE001 - never let this be the thing that fails
        # Only reachable for a wx that raises rather than exiting. The
        # display-less case is handled above, because it does not raise.
        print(f"note: no wxApp ({exc}); pcbnew path lookups may assert", file=sys.stderr)
